server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  # Nộp tối đa 10 file x 25MB mỗi lần (Nginx mặc định chỉ cho 1MB)
  client_max_body_size 260m;

  location /api/ {
    proxy_pass http://api:5000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /socket.io/ {
    proxy_pass http://api:5000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  # React Router: mọi đường dẫn khác trả về index.html
  location / {
    try_files $uri /index.html;
  }
}
